version: '2'

services:
    boilerplatebackend:
        volumes:
            - .:/boilerplate

            # necessary to prevent OS X node_modules being loaded in:
            - /boilerplate/backend/node_modules
        environment:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY

        build:
            context: ./backend
            dockerfile: ./Dockerfile

        ports:
          - "8080:8080"